DROP DATABASE IF EXISTS Coupons;

CREATE DATABASE Coupons;
USE Coupons;

CREATE TABLE users (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(100) NOT NULL
);

CREATE TABLE urls (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	last_price DECIMAL(10,2),
	last_price_update DATETIME,
	url VARCHAR(1000) NOT NULL,
	user_id INTEGER NOT NULL,
	FOREIGN KEY fk_user(user_id) REFERENCES users(id) ON DELETE CASCADE
);
